
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#if !defined(_LIBXFCE4PANEL_INSIDE_LIBXFCE4PANEL_H) && !defined(LIBXFCE4PANEL_COMPILATION)
#error "Only <libxfce4panel/libxfce4panel.h> can be included directly, this file may disappear or change contents"
#endif

#ifndef __LIBXFCE4PANEL_ENUM_TYPES_H__
#define __LIBXFCE4PANEL_ENUM_TYPES_H__
#include <glib-object.h>
G_BEGIN_DECLS
/* enumerations from "libxfce4panel-enums.h" */
GType xfce_panel_plugin_mode_get_type (void) G_GNUC_CONST;
#define XFCE_TYPE_PANEL_PLUGIN_MODE (xfce_panel_plugin_mode_get_type())
GType xfce_screen_position_get_type (void) G_GNUC_CONST;
#define XFCE_TYPE_SCREEN_POSITION (xfce_screen_position_get_type())
G_END_DECLS

#endif /* !__LIBXFCE4PANEL_ENUM_TYPES_H__ */

/* Generated data ends here */

