
/* This file is generated by glib-mkenums, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */

#if !defined(_LIBXFCE4UI_INSIDE_LIBXFCE4UI_H) && !defined(LIBXFCE4UI_COMPILATION)
#error "Only <libxfce4ui/libxfce4ui.h> can be included directly, this file is not part of the public API."
#endif

#ifndef __LIBXFCE4UI_ENUM_TYPES_H__
#define __LIBXFCE4UI_ENUM_TYPES_H__
#include <glib-object.h>

G_BEGIN_DECLS
/* enumerations from "libxfce4ui-enums.h" */
GType xfce_sm_client_error_enum_get_type(void) G_GNUC_CONST;
#define XFCE_TYPE_SM_CLIENT_ERROR_ENUM (xfce_sm_client_error_enum_get_type())
GType xfce_sm_client_restart_style_get_type(void) G_GNUC_CONST;
#define XFCE_TYPE_SM_CLIENT_RESTART_STYLE (xfce_sm_client_restart_style_get_type())
GType xfce_sm_client_shutdown_hint_get_type(void) G_GNUC_CONST;
#define XFCE_TYPE_SM_CLIENT_SHUTDOWN_HINT (xfce_sm_client_shutdown_hint_get_type())
GType xfce_icon_view_drop_position_get_type(void) G_GNUC_CONST;
#define XFCE_TYPE_ICON_VIEW_DROP_POSITION (xfce_icon_view_drop_position_get_type())
GType xfce_icon_view_layout_mode_get_type(void) G_GNUC_CONST;
#define XFCE_TYPE_ICON_VIEW_LAYOUT_MODE (xfce_icon_view_layout_mode_get_type())
GType xfce_item_list_model_flags_get_type(void) G_GNUC_CONST;
#define XFCE_TYPE_ITEM_LIST_MODEL_FLAGS (xfce_item_list_model_flags_get_type())
GType xfce_item_list_model_column_get_type(void) G_GNUC_CONST;
#define XFCE_TYPE_ITEM_LIST_MODEL_COLUMN (xfce_item_list_model_column_get_type())
GType xfce_item_list_view_column_get_type(void) G_GNUC_CONST;
#define XFCE_TYPE_ITEM_LIST_VIEW_COLUMN (xfce_item_list_view_column_get_type())
G_END_DECLS

#endif /* !__LIBXFCE4UI_ENUM_TYPES_H__ */

/* Generated data ends here */

