/* This file is generated by glib-genmarshal, do not modify it. This code is licensed under the same license as the containing project. Note that it links to GLib, so must comply with the LGPL linking clauses. */
#ifndef __XKL_ENGINE_MARSHAL_H__
#define __XKL_ENGINE_MARSHAL_H__

#include <glib-object.h>

G_BEGIN_DECLS

/* VOID:VOID (./marshal.list:1) */
#define xkl_engine_VOID__VOID	g_cclosure_marshal_VOID__VOID

/* INT:LONG,LONG (./marshal.list:2) */
extern
void xkl_engine_INT__LONG_LONG (GClosure     *closure,
                                GValue       *return_value,
                                guint         n_param_values,
                                const GValue *param_values,
                                gpointer      invocation_hint,
                                gpointer      marshal_data);

/* VOID:ENUM,INT,BOOLEAN (./marshal.list:3) */
extern
void xkl_engine_VOID__ENUM_INT_BOOLEAN (GClosure     *closure,
                                        GValue       *return_value,
                                        guint         n_param_values,
                                        const GValue *param_values,
                                        gpointer      invocation_hint,
                                        gpointer      marshal_data);


G_END_DECLS

#endif /* __XKL_ENGINE_MARSHAL_H__ */
